#!/usr/bin/perl

use lib qw(lib);
use strict;
use warnings;

use IO::Socket;
use IO::Socket::INET;
use Razor2::Client::Agent;

my $sock = IO::Socket::INET->new(
	LocalAddr => 'localhost',
	LocalPort => 9192,
	Proto     => 'tcp',
	ReuseAddr => 1,
	Listen    => 5,
);

# quiet warning
my $dummy = $Razor2::Client::Agent::errstr;

while(my $conn = $sock->accept()) {
	my $agent = new Razor2::Client::Agent('razor-check')
		or die $Razor2::Client::Agent::errstr;
	$agent->do_conf() or die $agent->errstr ."\n";

	my $resp = $agent->doit( {fh=>$conn} );

	if ($resp == 0) {
		print STDERR "razorsocket: mail detected as spam\n";
		print $conn "spam";
	} else {
		print $conn "ham";
	}

	$conn->close();
}

$sock->close();
exit 0;

